SERVER:
  DATABASE_PATH:
    env: MATTER_SERVER_DATABASE_PATH
    default: "battlecontrol.db"
  HOST:
    env: MATTER_SERVER_HOST
    default: "127.0.0.1"
  PORT:
    env: MATTER_SERVER_PORT
    default: "3000"
  WEBAUTHN:
    RP_ID:
      env: MATTER_SERVER_WEBAUTHN_RP_ID
      default: "localhost"
    ORIGIN:
      env: MATTER_SERVER_WEBAUTHN_ORIGIN
      default: "http://localhost:3000"
    ALLOWED_ORIGINS:
      env: MATTER_SERVER_WEBAUTHN_ALLOWED_ORIGINS
      default: "http://localhost:5173,http://localhost:5175"
